# Generated by Django 5.0.4 on 2024-07-20 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_organization_end_day_organization_start_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlocationstatus',
            old_name='geofence_id',
            new_name='geofence',
        ),
        migrations.RenameField(
            model_name='userlocationstatus',
            old_name='user_id',
            new_name='user',
        ),
    ]
