# Generated by Django 5.0.4 on 2024-07-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_geofence_id_userlocationstatus_geofence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersalary',
            name='monthly_salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='organization',
            name='end_day',
            field=models.CharField(default='Friday', max_length=10),
        ),
        migrations.AlterField(
            model_name='organization',
            name='start_day',
            field=models.CharField(default='Monday', max_length=10),
        ),
    ]
