# Generated by Django 5.0.4 on 2024-07-21 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_usersalary_monthly_salary_alter_organization_end_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersalary',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.organization'),
        ),
    ]
