# Generated by Django 5.0.4 on 2024-07-22 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_usersalary_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end_shift',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start_shift',
            field=models.TimeField(),
        ),
    ]
