# Generated by Django 5.0.4 on 2024-07-24 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_salary_user_alter_userlocationstatus_geofence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocationstatus',
            name='geofence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.geofences'),
        ),
    ]
