# Generated by Django 5.0.4 on 2024-07-24 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_userlocationstatus_geofence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlocationstatus',
            name='geofence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.geofences'),
        ),
    ]
