# Generated by Django 5.0.4 on 2024-07-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_userlocationstatus_geofence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('monitored', 'Monitored')], max_length=20),
        ),
    ]
